version: "3.9"

services:
  postgres:
    container_name: db_hire_go
    image: postgres:14.5
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
    ports:
      - "5432:5432"
    volumes:
      - apigo:/var/lib/postgresql/data

volumes:
  apigo:
